### PR TITLE
JDK-8211399: libxslt fails to build with glibc 2.26(#234)

### PR DESCRIPTION
**Pull request by ararunprasad**
https://github.com/javafxports/openjdk-jfx/issues/234

### CODE REVIEW

**Comment by kevinrushforth** [comment]
JBS issue: https://bugs.openjdk.java.net/browse/JDK-8211399

**Comment by kevinrushforth** [comment]
Will this cause `locale.h` to be included instead? You hinted at that in #234.

Btw, don't forget to send an RFR to openjfx-dev.

**Comment by johanvos** [comment]
looks good, the only thing I'm a bit confused about is the commented #undef?

**Comment by ararunprasad** [comment]
It is already been merged with upstream mercurial repo:

Changeset: 94f51e852ad6
Author:    arajkumar
Date:      2018-12-20 18:42 +0530
URL:       http://hg.openjdk.java.net/openjfx/jfx-dev/rt/rev/94f51e852ad6

8211399: libxslt fails to build with glibc 2.26
Reviewed-by: jvos, mbilla, kcr

**Comment by ararunprasad** [comment]
It is already been merged with upstream mercurial repo:

Changeset: 94f51e852ad6
Author: arajkumar
Date: 2018-12-20 18:42 +0530
URL: http://hg.openjdk.java.net/openjfx/jfx-dev/rt/rev/94f51e852ad6

8211399: libxslt fails to build with glibc 2.26
Reviewed-by: jvos, mbilla, kcr

**Pull request closed without merging**
