### PR TITLE
use DPIUtil to get the scale-factor SWT is running in

### LINKED ISSUE #33: FXCanvas on Win32 HiDPI produces wrong results
This is logged as https://bugs.openjdk.java.net/browse/JDK-8191661 but I never managed to get the webref tool running

### PR DESCRIPTION
**Pull request by tomsontom**
fixes #33

### CODE REVIEW

**Comment by kevinrushforth** [comment]
Proposed fix is for [JDK-8191661](https://bugs.openjdk.java.net/browse/JDK-8191661)

**Comment by johanvos** [comment]
javafx.scene.control.TextInputControlTest seems to fail with this PR. Any idea?

**Comment by tomsontom** [comment]
not really but I can rerun the build on ny windows machine (IIRC i ran a build before pushing and there've been no test error)

**Comment by tomsontom** [comment]
BTW: The fix is in FXCanvas so I don't see how that could make test in the control-space fail (I assume they are not running against FXCanvas and SWT)

**Comment by kevinrushforth** [comment]
One minor formatting nit remains: `if(cond)` should be `if (cond)`
Otherwise this looks good.

Can you also rebase it to the latest develop branch and see if the test passes? I agree that there is no way your change could have affected the failing test.

**Comment by johanvos** [comment]
@tomsontom can you add that formatting change requested by Kevin? This will also trigger travis to redo the CI.

**Comment by tomsontom** [comment]
I messed things up when I rebased the stuff - I'll abandon this PR and create a new one

**Comment by tomsontom** [comment]
I opened PR #100

**Pull request closed without merging**
