### PR TITLE
JDK-8226789: Path rendered incorrectly when it goes outside the clipping region

### PR DESCRIPTION
**Pull request by bourgesl**
Changes:
- Stroker: fixed closePath() to preserve last position and its outcode
- TransformingPathConsumer2D: fixed PathClipFilter.closePath() to preserve last position and its outcode
- Dasher: better precision handling (comparison float value with epsilon)
- ClipShapeTest: use preliminary curve subdivision (length > 50px) to avoid false positives on long stroked curves (quad / cubic) + lowered thresholds

### CODE REVIEW

**Comment by kevinrushforth** [comment]
JBS issue: https://bugs.openjdk.java.net/browse/JDK-8226789

**Comment by kevinrushforth** [comment]
@mrserb can you also review this?

**Comment by bourgesl** [comment]
Thanks kevin,
I reverted few changes in DStroker related to numerical precision to make RT_5300 test  pass, sorry, CI is precious in such test coverage: branch + CI are OK.

FYI I improved the ClipShapeTest to reproduce the initial PathBug issue (closePath followed by curveTo) so I did not add any new test as the bug is now covered by ClipShapeTest. As usual, the tesing phase was very time consuming to do it right.
Morevover, this test detected another regression (same case) in Stroker although the PathBug test only covers shape fills.

Laurent

**Comment by kevinrushforth** [comment]
I'll plan to review this tomorrow.

**Comment by bourgesl** [comment]
> Looks fine, but probably it would be better to separate the changes for closePath and precision with separate corresponding tests.

I agree with Sergey. However I fixed precision in Dasher (EPS = 1E-6) during my work on the ClipShapeTest class to validate all these changes (long & tedious) so this patch constitutes one unit of work and is properly tested (according to me)

**Comment by bourgesl** [comment]
I will fix comments before pushing.

Where ? In hg repo (master) or should we merge the PR first ?
Sorry I do not remember the workflow

**Comment by kevinrushforth** [comment]
You can do it one of two ways, it's up to you which one:

1. First merge the PR and then push the *identical* patch to HG (with a fixed-up commit message, of course). The steps are:
* Make sure that the PR has all of your intended changes (e.g., you would need to push the fixup for the typo in the comment to your git branch)
* Merge this PR
* Export the GIT commit patch and import it into HG with a correct message
* Run `hg jcheck` to confirm
* Push the HG changeset to [jfx-dev/rt](https://hg.openjdk.java.net/openjfx/jfx-dev/rt)

2. Push to HG and ignore this PR (it will be synced down to the develop branch within an hour)
* Locally fix the typo in the comment
* Export the GIT commit patch and import it into HG with a correct message
* Run `hg jcheck` to confirm
* Push the HG changeset to [jfx-dev/rt](https://hg.openjdk.java.net/openjfx/jfx-dev/rt)
* Close the PR without merging it

**Comment by bourgesl** [comment]
Thank you for your reviews,
I will push tomorrow on hg master, 
I will be very careful while upgrading my local copy & merging changesets.

**Comment by bourgesl** [comment]
Changeset: 6ca3e8aadafc
Author:    lbourges
Date:      2019-07-25 09:54 +0200
URL:       https://hg.openjdk.java.net/openjfx/jfx-dev/rt/rev/6ca3e8aadafc

**Pull request closed without merging**
