### PR TITLE
[RDY] Fix Appveyor build.

### PR DESCRIPTION
**Pull request by brcolow**
Just currently experimenting with fixing the Appveyor build. Continuation of #3

### CODE REVIEW

**Comment by brcolow** [comment]
Doesn't look like Appveyor can see this PR, so I can not easily debug on my end.

**Comment by tiainen** [comment]
Let me see if I can enable building PR in Appveyor.

**Comment by tiainen** [comment]
@brcolow Could you try pushing something again?

**Comment by brcolow** [comment]
Okay. I will try and devote time to work on this in the next couple days.

**Comment by bourgesl** [comment]
How to configure appveyor integration to build pull requests ? 
Only travis CI was run.

**Comment by brcolow** [comment]
Make sure that on the repository settings it lists the Appveyor webhook.

Go to this repositories settings, then click on the Webhooks menu item.

If Appveyor webhook is not listed, it must be added:

url: https://ci.appveyor.com/api/github/webhook 
on `pull_request` and `push`.

**Comment by tiainen** [comment]
The webhook was indeed missing before. I re-added the project in Appveyor and now it seems to be all correct. I think I messed up a bit the first time with authorization, because it asked me a few times.

screen shot 2018-03-02 at 10 30 17

**Comment by brcolow** [comment]
Okay, looks like the check is being picked up now. Cool. This will allow me to work on this more easily. Will try and fix this in the next couple days. Will be experimenting in this PR for a while, then will squash/rebase to one commit.

**Comment by tiainen** [comment]
Perfect, looking forward to it!

**Comment by brcolow** [comment]
Okay, I was able to make some changes that now allow for the Windows build to work. There are some failing tests, but the entire test suite is ran and the test results are uploaded to Appveyor so this is now working as intended.

**Comment by bourgesl** [comment]
Hi Michael,
You're right: it works i.e. appveyor is building openjfx + tests.

However, test result upload failed on appveyor:
```
Uploading test results to AppVeyor…
Get-ChildItem : Cannot find path 'C:\projects\openjdk-jfx\modules\javafx.jmx\build\test-results\test' because it does not exist.
At line:21 char:21
+ ... h ($file in Get-ChildItem ".\modules\${module}\build\test-results\tes ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\ope...st-results\test:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Cannot find path 'C:\projects\openjdk-jfx\modules\javafx.media\build\test-results\test' because it does not exist.
At line:21 char:21
+ ... h ($file in Get-ChildItem ".\modules\${module}\build\test-results\tes ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\ope...st-results\test:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Cannot find path 'C:\projects\openjdk-jfx\modules\javafx.swing\build\test-results\test' because it does not exist.
At line:21 char:21
+ ... h ($file in Get-ChildItem ".\modules\${module}\build\test-results\tes ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\ope...st-results\test:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Get-ChildItem : Cannot find path 'C:\projects\openjdk-jfx\modules\javafx.swt\build\test-results\test' because it does not exist.
At line:21 char:21
+ ... h ($file in Get-ChildItem ".\modules\${module}\build\test-results\tes ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\ope...st-results\test:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Command executed with exception: Cannot find path 'C:\projects\openjdk-jfx\modules\javafx.swt\build\test-results\test' because it does not exist.
```

**Comment by brcolow** [comment]
Some fail, yes. But as you can see 30,004 test results are uploaded. I tried to swallow the errors from uploading the results but some still get through (I am not sure why/how).

**Comment by brcolow** [comment]
I pushed some new changes that try and catch, then swallow the exception. We'll see if that works for just ignoring those errors.

**Comment by brcolow** [comment]
Okay, the errors are now not printed.

**Comment by bourgesl** [comment]
Will have look later...
One simple comment: I would like the appveyor build status is failed ONLY if jfx build & test failed, never if the test uploads fail.
Is it possible to have intermediate build return codes (ok, ko, warn...) ?

**Comment by brcolow** [comment]
The way it is now the appveyor build will *not* fail if the test uploads fail.

**Comment by bourgesl** [comment]
2 excellent news:
- openjfx build works on github
- appveyor CI runs tests and it detects test faiures (print issues), it should be fixed in openjfx first
That's perfect for me and thank you a lot for making CI scripts.
Please approve this PR, it is very good for me.
Congratulations

**Comment by bourgesl** [comment]
I propose to fix the openjfx bug using a new github PR (new community process) as it consists in fixing NPE...

Any volunteer ?
See https://bugs.openjdk.java.net/browse/JDK-8196617

**Comment by johanvos** [comment]
This is indeed good news, it shows the process is working. But why is Travis passing? Doesn't that run the tests, or are the failures windows-only? 
(this is not related to the PR so I'll merge this)

**Pull request merged**
