### PR TITLE
JDK-8210859: Update sym-link in release notes for JavaFX 11

### PR DESCRIPTION
**Pull request by jesuino**
Link was broken, I don't know if I am using the correct one..

### CODE REVIEW

**Comment by kevinrushforth** [comment]
The link looks correct to me. I was planning to do this anyway once I got confirmation from the Gluon folks that this was the best URL to use. This will need a JBS issue, and will need to be targeted to openjfx11 so that the live release notes are updated. I will file one.

**Comment by kevinrushforth** [comment]
I filed [JDK-8210859](https://bugs.openjdk.java.net/browse/JDK-8210859) to track this.

**Comment by kevinrushforth** [comment]
@jesuino I note that for a trivial / obvious correction such as this, we can merge it without an OCA, but in that case we would not provide any attribution to you. Let us know what you want to do. If you would like to contribute further to OpenJFX, you will need to sign the OCA anyway, so it would be good to get the process started now.

**Comment by eugener** [comment]
The changes are trivial, so I approved.. but I see Windows CI failing?

**Comment by jesuino** [comment]
> @jesuino I note that for a trivial / obvious correction such as this, we can merge it without an OCA, but in that case we would not provide any attribution to you. Let us know what you want to do. If you would like to contribute further to OpenJFX, you will need to sign the OCA anyway, so it would be good to get the process started now.

That's fine, please feel free to merge it without any attribution, I just wanted to correct the URL, later if I contribute more I can sign the OCA, thanks!

**Comment by kevinrushforth** [comment]
Regarding the CI failure, I see the following in the log:

```
Command executed with exception: Cannot find path
'C:\projects\openjdk-jfx\modules\javafx.fxml\build\test-results\test' because it does not exist.
```

This looks like a spurious failure, but unrelated to the change.

**Comment by kevinrushforth** [comment]
Oh, I see the real problem with the failure. This PR was mistakenly made against `jfx-11` rather than develop! I should have caught this and required the base branch to be changed to `develop`. PRs should *never* go into `jfx-11` directly.

Fortunately, this commit was destined for 11-dev / jfx-11 anyway, so no harm done. This time...I'll let that be a lesson to me to check the base more carefully.

In any case, the real reason for the failure is that the jfx-11 branch does not have the fix for [JDK-8210219](https://bugs.openjdk.java.net/browse/JDK-8210219), which went into openjfx12. The lack of that fix causes the following failure:

```
[00:11:06] C:\projects\openjdk-jfx\modules\javafx.graphics\src\main\native-glass\win\GlassClipboard.cpp(86): error C2065: '_HASH_SEED': undeclared identifier
```

**Comment by eugener** [comment]
Should this branch be protected ?

Eugene
________________________________

**Comment by kevinrushforth** [comment]
> Should this branch be protected ?

Perhaps, but since I need to push changes as part of the mistake, and the mistake was mine, I don't know it would have helped in this case.

**Pull request merged**
