### PR TITLE
JDK-8210691: Deliver release notes for JavaFX 11

### PR DESCRIPTION
**Pull request by kevinrushforth**
Here is the final draft of the JavaFX 11 release notes. The content is ready for review, but we still need to decide where to host it before it can be merged.

### CODE REVIEW

**Comment by kevinrushforth** [comment]
The easiest way to review it is to look at the new [release-notes-11.md](https://github.com/kevinrushforth/openjdk-jfx/blob/release-notes/doc-files/release-notes-11.md) fille.

**Comment by kevinrushforth** [comment]
Question for reviewers: should the table of fixed bugs/enhancements be sorted by sub-component?

**Comment by kevinrushforth** [comment]
Regardless of where we host this, we want to put it under version control in the openjfx/11-dev repo. I filed [JDK-8210691](https://bugs.openjdk.java.net/browse/JDK-8210691) to track this.

**Comment by tiainen** [comment]
* I'm in favour of sorting the table by subcomponent.
* Regardless of where the release notes will be hosted, having them in the code repository is indeed a must. It allows anyone to link directly to the release notes.

**Comment by nlisker** [comment]
Sorted table looks good.

Are the listed changes user-facing only? On one hand, I don't see [JDK-8196198 Remove obsolete apps/experiments](https://bugs.openjdk.java.net/browse/JDK-8196198https://bugs.openjdk.java.net/browse/JDK-8196198), on the other hand, I see [JDK-8196130 Eclipse configuration files need to be updated](https://bugs.openjdk.java.net/browse/JDK-8196130).

**Comment by kevinrushforth** [comment]
> Are the listed changes user-facing only?

That was roughly the intent. I excluded the build and samples subcategories as well as bugs labeled with testbug, noreg-self, or noreg-demo.

Perhaps we could start using the "Task" issuetype for IDE-only changes, since they don't touch anything that could affect the build. In any case, I'll manually exclude that one.

**Comment by kevinrushforth** [comment]
I changed [JDK-8196130](https://bugs.openjdk.java.net/browse/JDK-8196130) to a Task. I also found one more bug that should be excluded, since it is a test bug, but was missing the label (I added it).

[JDK-8170026](https://bugs.openjdk.java.net/browse/JDK-8170026) - Some tests in RegionBackgroundFillUITest fail with fractional window scale

The above two bugs no longer appear in my query. I will remove both of them from the table.

**Comment by kevinrushforth** [comment]
Having nothing to do with this change... I see that the Travis CI build failed. This failure is due to a network error affecting jdk.java.net and openjdk.java.net. It seems the only reason the Appveyor build didn't fail is that an error in the download doesn't fail the build, and the build machine in question happened to have a jdk11 installed from a previous build.

In any case, "they" know about the network problem and are working on it.

**Pull request merged**
