### PR TITLE
JDK-8215775: Scrollbars from web pages appear to be absolute, overlapping everything

### PR DESCRIPTION
**Pull request by arajkumar**
Linked JBS issue: https://bugs.openjdk.java.net/browse/JDK-8215775

### CODE REVIEW

**Review by kevinrushforth — COMMENTED** [review]
Looks good to me. I presume you have made sure that this fix doesn’t reintroduce [JDK-8203698](https://bugs.openjdk.java.net/browse/JDK-8203698)?

**Comment by ararunprasad** [comment]
Thanks @kevinrushforth. Though the fix is not introducing any regressions, still I see the old behaviour(as same as without this fix). Still working on a right fix.

**Comment by ararunprasad** [comment]
@kevinrushforth @muralibilla , Please take a look. Just updated this PR with proper overlay scrollbar implementation derived from GTK WebKit.

**Comment by kevinrushforth** [comment]
This looks promising, but as it is a new implementation for overlay scrollbars, it is probably best to let it bake for a while (so target for openjfx13 rather than 12). It will need to be well-tested on all three platforms.

**Comment by kevinrushforth** [comment]
@ararunprasad Can you send an RFR email to openjfx-dev?

**Comment by ararunprasad** [comment]
> @ararunprasad Can you send an RFR email to openjfx-dev?

Thanks for the reminder Kevin. I sent the RFR email.

**Review by kevinrushforth — APPROVED** [review]

**Review by muralibilla — APPROVED** [review]

**Comment by Merudo** [comment]
Is this fix missing from openjfx14? The scrollbar bug is present in the newest version.

**Comment by kevinrushforth** [comment]
The fix for this bug is present in OpenJFX 14 and 15-ea. I just now ran the test case from the bug report and it looks fine to me. If you have a failing test case, please file a new bug at [bugreport.java.com](https://bugreport.java.com/).

Btw, as noted in the README, this project (javafxports/openjdk-jfx) is no longer active. OpenJFX development has moved to the [openjdk/jfx](https://github.com/openjdk/jfx) GitHub project.

**Pull request merged**
