### PR TITLE
WIP: removed eclipse & idea project files

### PR DESCRIPTION
**Pull request by hendrikebbers**
removed first IDE based files as described in https://github.com/javafxports/openjdk-jfx/issues/4

### CODE REVIEW

**Comment by timo0** [comment]
can you pleas also extend the gitignore that the files won’t added again?

**Comment by hendrikebbers** [comment]
@timo0 done ;)

**Comment by eugener** [comment]
Removing files is easy. But has the testing with those IDEs been done?

**Comment by hendrikebbers** [comment]
@eugener If you want to use it in your IDE you should setup it on your own. I have not tested it until now but will try a setup for idea tomorrow. No idea about eclipse.
Will add WIP to to title ;)

**Comment by johanvos** [comment]
We should have confirmation for NetBeans/Eclipse/IntelliJ and then we can merge this PR.

**Comment by hendrikebbers** [comment]
More or less the same as https://github.com/javafxports/openjdk-jfx/pull/28 but @aalmiray added a better .gitignore file. Based on that I will close this PR. https://github.com/javafxports/openjdk-jfx/pull/28 should be merged.

**Pull request closed without merging**
