### PR TITLE
Move github related files under .github folder

### PR DESCRIPTION
**Pull request by eugener**
This PR is related to discussion on issue #6

### CODE REVIEW

**Comment by bourgesl** [comment]
Which README will be shown ?

**Comment by bourgesl** [comment]
I mean the hg repo had a readme...

**Comment by eugener** [comment]
This PR moves it to `.github` folder. So if it is not in the root - it will be shown from there.
Check it out in my fork at https://github.com/eugener/openjdk-jfx

**Comment by bourgesl** [comment]
There is a conflict as the openjfx hg forrest has a README file at root.
Having another one in .github/ is OK, but the first one will be displayed.

**Comment by eugener** [comment]
@kevinrushforth how important is to have the `README` file at the root in hg? Can we move it to `.github` folder here?

**Comment by kevinrushforth** [comment]
You mean the existing one (which is almost content-free)? That would seem odd in a .github directory, and since it doesn't really add any value, I think we can just remove it altogether.

**Comment by kevinrushforth** [comment]
The LICENSE, on the other hand, should remain at the top level. Will that cause problems?

**Comment by bourgesl** [comment]
Sorry to insist, but it is important for me to put some content (CI badges, links, description) in the README as described in #6 that is displayed on the homepage of the project, for example:
https://github.com/bourgesl/marlin-renderer
Newcomers need to understand what is this project

**Comment by johanvos** [comment]
I agree with @kevinrushforth and unless I'm missing something that should also fix the concerns from @bourgesl  : remove the README from the OpenJFX repository (there is no real content in there) and create a new README in .github that will be shown at the github homepage.
There might be some issues in syncing as the OpenJFX README has a history so it is somehow there, but that is something we can fix in the sync script.

**Comment by kevinrushforth** [comment]
If you remove the README file from top of the repo and then create a brand new README.md file in .github dir, then I would think there should be no problems w.r.t. history. Or is the concern that the patch already moved the existing README from top level to .github? In that case, yeah, you will need to fix it up somehow.

And just to check, there is no need to move the LICENSE file, right? We could (if needed) duplicate it in .github but it does need to be at the top of the repo.

**Comment by johanvos** [comment]
I think the LICENSE can indeed just stay where it is.

**Comment by eugener** [comment]
I will update the PR based on comments here

**Comment by eugener** [comment]
To keep the commit history clean I'm closing this pull request. The new one will be referenced from the  related issue #6

**Pull request closed without merging**
