### PR TITLE
JDK-8220222: improve gradle project dependencies specifications

### PR DESCRIPTION
**Pull request by christianheilmann**
In order to import the openjdk-jfx project correctly in the different IDEs, the dependencies should be clearly defined. At the moment the project is working in IDEA and Netbeans correctly. 

Currently,  Netbeans has an issue open with gradle and jigsaw (https://issues.apache.org/jira/browse/NETBEANS-2004 and https://github.com/kelemen/netbeans-gradle-project/issues/417). 

So the only IDE working 100% correctly is IDEA for importing the openjdk-jfx project.

Eclipse has a lot of problems with gradle and jigsaw.

### CODE REVIEW

**Comment by kevinrushforth** [comment]
You will need to file a new bug in JBS for this. Every changeset needs its own bug ID.

**Comment by kevinrushforth** [comment]
Please also read [CONTRIBUTING.md](https://github.com/javafxports/openjdk-jfx/blob/develop/.github/CONTRIBUTING.md). Also, if you haven't already submitted an OCA, please do so (there is a pointer in CONTRIBUTING.md).

Thanks.

**Comment by Ciruman** [comment]
Hi @kevinrushforth , @christianheilmann is a software engineer at Carl Zeiss Meditec. I created the issue JDK-9059624.

**Comment by Ciruman** [comment]
@kevinrushforth is JDK-9059624 not correctly created?

**Comment by Ciruman** [comment]
Here there is a JDK we can use: JDK-8220222 (https://bugs.openjdk.java.net/browse/JDK-8220222)

**Comment by kevinrushforth** [comment]
@Ciruman Thank you for the info about the OCA.

@christianheilmann please send an RFR to the openjfx-dev mailing list for this PR.

**Comment by kevinrushforth** [comment]
I see that you closed this. Does this mean that you are no longer interested in proposing this patch?

**Comment by christianheilmann** [comment]
We moved this change to a new pull request -> JDK-8220222: specify clearly gradle project dependencies #401
We are interested in this change :-)

**Comment by kevinrushforth** [comment]
Ah, I see it now. Thanks.

**Pull request closed without merging**
