### PR TITLE
[WIP] Try building javafx.web module

### PR DESCRIPTION
**Pull request by arajkumar**
Newly upgraded WebKit 606.1 supports unified source build which significantly reduces the build time.

### CODE REVIEW

**Comment by ararunprasad** [comment]
Note: This is for experimental purpose only, just to evaluate whether we could build javafx.web with new unified source changes.

**Comment by kevinrushforth** [comment]
Note that the Travis and Appveyor CI builds don't build webkit.

**Comment by kevinrushforth** [comment]
Please ignore my last (now deleted) comment. :)

**Comment by scientificware** [comment]
I confirm, it's very impressive. Thank you.

**Comment by scientificware** [comment]
I had also get a problem when trying to build WebCore.
My previous config didn't work no more because of ant or a missing of java version.
After having install ant 1.9.12 and Java 8 the build works fine.
Previously, I used the ant version provide by gradle.
One of these solved the problem.

**Comment by brcolow** [comment]
Just an FYI, without `DebugNative` the PDB debugging symbols won't be generated and uploaded on Windows. Currently we are not uploaded the debugging symbols generated on the Travis builds, so that should be okay but it will reduce test logging verbosity which could make working on PRs more difficult (for those that touch native code). What is the time is the `CONF` is kept at DebugNative?

**Comment by ararunprasad** [comment]
@brcolow As of now I'm just experimenting to see whether it is possible to enable WebKit compilation with Travis time constrains. I'm not sure about the time taken to build with CONF=DebugNative, locally it is around 1.5 times of Release build.

**Comment by ararunprasad** [comment]
Linux build proceeds upto 89% and macOS builds upto 95% before getting timed out. Looks like Windows is failing because of missing cygwin. I'm looking for some build optimisation techniques to reduce the time.

**Comment by brcolow** [comment]
cygwin is installed on Appveyor, it may be a PATH issue.

**Comment by ararunprasad** [comment]
With more files(32) on unified bundle, on macOS jfxwebkit library was build and terminates while building DRT.

**Comment by brcolow** [comment]
FWIW I messed around with trying to get ccache to work for the JavaFX build - never could because ccache was never called by the native compilation step in gradle.

**Comment by johanvos** [comment]
Can we separate the job that builds libjfxwebkit so that it gets the full amount of available time?

**Comment by ararunprasad** [comment]
@johanvos. Probably if we cache the generated JNI headers, native module has dependency only on the JNI headers.

**Comment by johanvos** [comment]
Would it make sense (in the longer term) to separate the building of the native library into a different project, where the generated JNI headers are imported as a dependency (generated by the main project)?

**Comment by ararunprasad** [comment]
@johanvos, it would. But still 50minutes time limit imposed by Travis will not be sufficient to build WebKit.

**Comment by kevinrushforth** [comment]
Closing this old experimental PR given that this sandbox repo will be retired soon. See [this message](https://mail.openjdk.java.net/pipermail/openjfx-dev/2019-September/023551.html).

**Pull request closed without merging**
