### PR TITLE
RaspberryPI build fixes

### PR DESCRIPTION
**Pull request by imario42**
Build JFX on PI + a wr_bcm_host_init to allow dispman calls

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@imario42 Please change this PR to be against the 'develop' branch rather than 'master'. Also, we will need a bug filed in JBS (unless there already is one), that you can reference.

**Comment by johanvos** [comment]
With https://github.com/javafxports/openjdk-jfx/commit/fc27da0570f510bb3c411b460620872b007fdd4e the swing-issue should be solved.
Can you file a bug in JBS so that we can discuss the dispman changes?

**Comment by kevinrushforth** [comment]
@imario42 Do you still want to merge this PR? If so, please file a bug in JBS and change the PR to be against the javafxports:develop branch.

**Comment by imario42** [comment]
* I've create a new PR https://github.com/javafxports/openjdk-jfx/pull/120
* OCA sent (not yet processed)
* JBS does not yet let me in, going to figure this out

**Pull request closed without merging**
