### PR TITLE
JDK-8216470: Some methods of System.Logger are unimplemented in PlatformLogger

### PR DESCRIPTION
**Pull request by ararunprasad**
Following methods are unimplemented, 

    @Override 
    public String getName() { 
       throw new UnsupportedOperationException("not implemented"); 
    } 

    @Override 
    public boolean isLoggable(System.Logger.Level level) { 
        throw new UnsupportedOperationException("not implemented"); 
    } 

    @Override 
    public void log(System.Logger.Level level, ResourceBundle bundle, String format, Object... params) { 
        throw new UnsupportedOperationException("not implemented"); 
    } 

    @Override 
    public void log(System.Logger.Level level, ResourceBundle bundle, String msg, Throwable thrown) { 
        throw new UnsupportedOperationException("not implemented"); 
    } 

Among those, getName() is used in JavaFX PerfLogger implementation. Implementing those would be trivial and straightforward.

### CODE REVIEW

**Comment by ararunprasad** [comment]
Following exception is thrown without this fix while enabling WebKit's perf logger.

Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
	at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:85)
	at javafx.web/com.sun.webkit.WebPage.twkInit(Native Method)
	at javafx.web/com.sun.webkit.WebPage.<init>(WebPage.java:199)
	at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:841)
	at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:826)
	at javafx.web/javafx.scene.web.WebView.<init>(WebView.java:260)
	at test.WebViewDemo.start(WebViewDemo.java:45)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.UnsupportedOperationException: not implemented
	at javafx.base/com.sun.javafx.logging.PlatformLogger.getName(PlatformLogger.java:121)
	at javafx.web/com.sun.webkit.perf.PerfLogger.fullName(PerfLogger.java:155)
	at javafx.web/com.sun.webkit.perf.PerfLogger.registerProbe(PerfLogger.java:201)
	at javafx.web/com.sun.webkit.perf.PerfLogger.startCount(PerfLogger.java:227)
	at javafx.web/com.sun.webkit.perf.PerfLogger.<init>(PerfLogger.java:90)
	at javafx.web/com.sun.webkit.perf.PerfLogger.getLogger(PerfLogger.java:57)
	at javafx.web/com.sun.webkit.perf.WCFontPerfLogger.<clinit>(WCFontPerfLogger.java:36)
	... 13 more
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.perf.WCFontPerfLogger
	at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:85)
	at javafx.web/com.sun.webkit.WebPage.twkInit(Native Method)
	at javafx.web/com.sun.webkit.WebPage.<init>(WebPage.java:199)
	at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:841)
	at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:826)
	at javafx.web/javafx.scene.web.WebView.<init>(WebView.java:260)
	at test.WebViewDemo.start(WebViewDemo.java:45)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.perf.WCFontPerfLogger
	at javafx.web/com.sun.javafx.webkit.prism.PrismGraphicsManager.getWCFont(PrismGraphicsManager.java:85)
	at javafx.web/com.sun.webkit.WebPage.twkInit(Native Method)
	at javafx.web/com.sun.webkit.WebPage.<init>(WebPage.java:199)
	at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:841)
	at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:826)
	at javafx.web/javafx.scene.web.WebView.<init>(WebView.java:260)
	at test.WebViewDemo.start(WebViewDemo.java:45)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)


Use the below log config to enable WebKit's Font Perf logger,
```
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL
com.sun.webkit.perf.WCFontPerfLogger.level = FINE

// Pass this flag to JVM: -Djava.util.logging.config.file=path/to/log.conf
```

**Comment by johanvos** [comment]
looks a trivial fix to me.

**Comment by ararunprasad** [comment]
> looks a trivial fix to me.

Indeed :)

**Comment by kevinrushforth** [comment]
@nlisker You might want to comment on this.

**Comment by nlisker** [comment]
Looks good.

There are still open questions about `PlatformLogger` at [JDK-8200236](https://bugs.openjdk.java.net/browse/JDK-8200236), so it could be that these changes will be irrelevant, but at least as a quick fix it's fine.

**Comment by ararunprasad** [comment]
@nlisker, I noticed when enabling WebKit's font perf log, till now I never attempted to enable it.

**Comment by kevinrushforth** [comment]
Pointer to JBS issue: [JDK-8216470](https://bugs.openjdk.java.net/browse/JDK-8216470).

**Comment by kevinrushforth** [comment]
I note that this was recently reported as issue #334 which has a pointer to [this StackOverflow](https://stackoverflow.com/questions/53908982/new-webview-causes-java-lang-unsupportedoperationexception-not-implemented/) query.

**Pull request merged**
