### PR TITLE
Created a basic .gitignore file

### LINKED ISSUE #21: Missing .gitignore file
There's a `.hgignore` file at the root but no corresponding `.gitignore` file.

### PR DESCRIPTION
**Pull request by kevinrushforth**
Fixes #21

### CODE REVIEW

**Comment by kevinrushforth** [comment]
NOTE: this should not be pushed upstream to hg.openjdk.java.net/openjfx

**Comment by eugener** [comment]
This file then has to be added to `.hgignore` IMO

**Comment by kevinrushforth** [comment]
You mean .gitignore ? it already is in .hgignore

**Comment by eugener** [comment]
I meant `.hgignore` - assumed  it is not there, but it is - my fault

**Comment by ararunprasad** [comment]
lgtm

**Pull request merged**
