### PR TITLE
JDK-8210092: Remove old javafx.swing implementation

### PR DESCRIPTION
**Pull request by kevinrushforth**
Fix for JBS issue [JDK-8210092](https://bugs.openjdk.java.net/browse/JDK-8210092).

This removes the old implementation for JDK 10 that depends on qualified exports, and changes javafx.swing to depend on jdk.unsupported.desktop unconditionally.

### CODE REVIEW

**Comment by kevinrushforth** [comment]
NOTE: this is not yet ready to merge. It is blocked by (JDK-8209966)[https://bugs.openjdk.java.net/browse/JDK-8209966], PR #174, which must be integrated first.

**Comment by kevinrushforth** [comment]
This is now ready for review.

Pending the review, this will be merged after [JDK-8209966](https://bugs.openjdk.java.net/browse/JDK-8209966), PR #174, is merged.

**Comment by kevinrushforth** [comment]
I pushed a minor change suggested by Prasanta to clean up the factory code by instantiating the InteropFactoryN class directly rather than looping over a list of 1 item and instantiating it using reflection.

**Comment by kevinrushforth** [comment]
I should add that I did a full build / test, plus running the manual FX / Swing interop tests on all three platforms.

**Comment by johanvos** [comment]
Builds/tests work fine on Linux.
@kevinrushforth  What are the FX/Swing interop tests you were running?

**Comment by kevinrushforth** [comment]
@johanvos in addition to the automated system tests (which includes a few JFXPanel and SwingNode tests), I have three simple "hello world" apps, two for JFXPanel and one for SwingNode, that I use during testing. I'm rather embarrassed to say that I never finished the effort of getting them into the repo and wiring them up to the build (actually, I did try to move one of them a while back, but it broke embedded builds). I'll file a bug to put these into apps/toys.

I also have a HelloFXCanvas program that should be added, but that one would take more work to wire up to the build.

**Comment by kevinrushforth** [comment]
Related to the above, we lack good tests for drag and drop between FX and Swing applications. This came up during the review of the refactored FX / Swing interop implementation so we could remove the dependency in internal Swing API. I'll file a separate bug to create such tests.

**Comment by johanvos** [comment]
It would be nice to have a sample on this as well, which can then be added to https://github.com/javafxports/jfx-samples once we really kick that off.

**Comment by kevinrushforth** [comment]
I forgot to mention that there is also a SwingInterop sample within Ensemble that uses JFXPanel. It doesn't run currently, since it tries to launch java in a separate process and doesn't pick up any command line args. I should file a bug on that as well.

**Comment by kevinrushforth** [comment]
I filed follow-on RFEs for the above issues:

[JDK-8211249](https://bugs.openjdk.java.net/browse/JDK-8211249) : Refactor javafx.swing implementation to get rid of unneeded abstraction layer
[JDK-8211248](https://bugs.openjdk.java.net/browse/JDK-8211248) : Create manual drag and drop tests for FX / Swing interop
[JDK-8211234](https://bugs.openjdk.java.net/browse/JDK-8211234) : Open-source simple test programs for FX / Swing interop
[JDK-8211247](https://bugs.openjdk.java.net/browse/JDK-8211247) : Open-source simple test programs for FX / SWT interop

**Pull request merged**
